accessControl:
    autologinAs: homeassistant
    autologinLocal: true
    localNetworks:
        - 172.30.32.2
folder:
    generated: /tmp/octoprint/generated
    timelapse_tmp: /tmp/octoprint/timelapse/tmp
server:
    commands:
        serverRestartCommand: /scripts/octoprint_restart.sh
        systemRestartCommand: /scripts/system_restart.sh
        systemShutdownCommand: /scripts/system_shutdown.sh
