accessControl:
    autologinAs: homeassistant
    autologinLocal: true
    localNetworks:
        - 172.30.32.2
folder:
    data: /data/octoprint/data
    generated: /data/octoprint/generated
    logs: /data/octoprint/logs
    plugins: /data/octoprint/plugins
    printerProfiles: /data/octoprint/printerProfiles
    scripts: /data/octoprint/scripts
    slicingProfiles: /data/octoprint/slicingProfiles
    timelapse_tmp: /tmp
    timelapse: /data/octoprint/timelapse
    translations: /data/octoprint/translations
    uploads: /data/octoprint/uploads
    virtualSd: /data/octoprint/virtualSd
    watched: /data/octoprint/watched
server:
    commands:
        serverRestartCommand: /scripts/octoprint_restart.sh
        systemRestartCommand: /scripts/system_restart.sh
        systemShutdownCommand: /scripts/system_shutdown.sh
webcam:
    ffmpeg: /usr/bin/ffmpeg
    snapshot: http://127.0.0.1:8080/?action=snapshot
    stream: webcam/?action=stream
system:
    actions:
        -   action: camerastart
            name: Start camera
            command: /scripts/camera_start.sh
        -   action: camerastop
            name: Stop camera
            command: /scripts/camera_stop.sh
events:
    enabled: true
    subscriptions:
    -   command: /scripts/camera_start.sh
        enabled: false
        event: Startup
        type: system
