build_from:
    armhf: fredrikbaberg/addon-octoprint-base-armhf:0.1.1
    armv7: fredrikbaberg/addon-octoprint-base-armv7:0.1.1
    amd64: fredrikbaberg/addon-octoprint-base-amd64:0.1.1
    aarch64: fredrikbaberg/addon-octoprint-base-aarch64:0.1.1
    i386: fredrikbaberg/addon-octoprint-base-i386:0.1.1
