# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base"
  amd64: "ghcr.io/home-assistant/amd64-base"
  armhf: "ghcr.io/home-assistant/armhf-base"
  armv7: "ghcr.io/home-assistant/armv7-base"
  i386: "ghcr.io/home-assistant/i386-base"
labels:
  org.opencontainers.image.title: "3DPrinter"
  org.opencontainers.image.description: "3DPrinter add-on for Home Assistant. OctoPrint, Klipper and more."
  org.opencontainers.image.source: "https://github.com/fredrikbaberg/hassio-addons/tree/master/3dprinter"
args:
  TEMPIO_VERSION: "2021.05.0"
