name: klipper

on:
  workflow_dispatch:
  push:
    tags:
      - klipper-v*

jobs:
  armhf:
    name: armhf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish
      uses: home-assistant/builder@master
      with:
        args: |
          --armhf \
          --target klipper
