name: octoprint-next-dev

on:
  workflow_dispatch:
  push:
    tags:
      - octoprint-next-dev-v*

jobs:
  armhf:
    name: armhf
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish
      uses: home-assistant/builder@master
      with:
        args: |
          --armhf \
          --docker-hub-check \
          --target octoprint-next-dev
  armv7:
    name: armv7
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish
      uses: home-assistant/builder@master
      with:
        args: |
          --armv7 \
          --docker-hub-check \
          --target octoprint-next-dev
  amd64:
    name: amd64
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and publish
      uses: home-assistant/builder@master
      with:
        args: |
          --amd64 \
          --docker-hub-check \
          --target octoprint-next-dev
